
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.somecompany;

import generated.NewDataSet;
import generated.NewDataSet.InventoryStatus;

import java.net.URL;
import java.util.logging.Logger;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Unmarshaller;

import org.w3._2001.xmlschema.LocalElement;
import org.w3._2001.xmlschema.Schema;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-11T20:31:07.601+02:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "InventoryInquiry",
                      portName = "InventoryInquirySoap",
                      targetNamespace = "http://www.somecompany.com/",
                      wsdlLocation = "file:/home/sergio/Programacion/workspaceLuna/TestJAXWS/src/InventoryInquiry.wsdl",
                      endpointInterface = "com.somecompany.InventoryInquirySoap")
                      
public class InventoryInquirySoapImpl implements InventoryInquirySoap {

    private static final Logger LOG = Logger.getLogger(InventoryInquirySoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.somecompany.InventoryInquirySoap#getInventoryStatus(java.lang.String  dealerCode ,)java.lang.String  supplierCode ,)java.lang.String  partNumber ,)int  quantity ,)java.lang.String  deliveryLocation )*
     */
    public GetInventoryStatusResponse.GetInventoryStatusResult getInventoryStatus(java.lang.String dealerCode,java.lang.String supplierCode,java.lang.String partNumber,int quantity,java.lang.String deliveryLocation) { 
        LOG.info("Executing operation getInventoryStatus");
        System.out.println(dealerCode);
        System.out.println(supplierCode);
        System.out.println(partNumber);
        System.out.println(quantity);
        System.out.println(deliveryLocation);
        try {
        	InventoryStatus ie = new InventoryStatus();
        	ie.setDeliveryLocation("del");
        	ie.setInStock(36);
        	ie.setEstDeliveryDate("09/27/2016");
        	ie.setDeliveryLocation("883620750");
        	
        	NewDataSet nds = new NewDataSet();
        	nds.getInventoryStatus().add(ie);
        	
        	GetInventoryStatusResponse.GetInventoryStatusResult _return = new GetInventoryStatusResponse.GetInventoryStatusResult();
        	
        	_return.setSchema(parseDiffgramSchema());
        	_return.setAny(nds);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    private Schema parseDiffgramSchema() throws JAXBException {
    	URL file = this.getClass().getClassLoader().getResource("diffgram-v1.xsd");
    	
    	JAXBContext jaxbContext = JAXBContext.newInstance(Schema.class);
    	
    	Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
    	
    	Schema schema = (Schema) jaxbUnmarshaller.unmarshal(file);

    	return schema;
    }
}
