
package com.somecompany;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventoryInquirySoap", targetNamespace = "http://www.somecompany.com/")
@XmlSeeAlso({
    com.somecompany.ObjectFactory.class,
    org.w3._2001.xmlschema.ObjectFactory.class
})
public interface InventoryInquirySoap {


    /**
     * 
     * @param quantity
     * @param deliveryLocation
     * @param dealerCode
     * @param partNumber
     * @param supplierCode
     * @return
     *     returns com.somecompany.GetInventoryStatusResponse.GetInventoryStatusResult
     */
    @WebMethod(action = "http://www.somecompany.com/getInventoryStatus")
    @WebResult(name = "getInventoryStatusResult", targetNamespace = "http://www.somecompany.com/")
    @RequestWrapper(localName = "getInventoryStatus", targetNamespace = "http://www.somecompany.com/", className = "com.somecompany.GetInventoryStatus")
    @ResponseWrapper(localName = "getInventoryStatusResponse", targetNamespace = "http://www.somecompany.com/", className = "com.somecompany.GetInventoryStatusResponse")
    public com.somecompany.GetInventoryStatusResponse.GetInventoryStatusResult getInventoryStatus(
        @WebParam(name = "DealerCode", targetNamespace = "http://www.somecompany.com/")
        String dealerCode,
        @WebParam(name = "SupplierCode", targetNamespace = "http://www.somecompany.com/")
        String supplierCode,
        @WebParam(name = "PartNumber", targetNamespace = "http://www.somecompany.com/")
        String partNumber,
        @WebParam(name = "Quantity", targetNamespace = "http://www.somecompany.com/")
        int quantity,
        @WebParam(name = "DeliveryLocation", targetNamespace = "http://www.somecompany.com/")
        String deliveryLocation);

}
